services:
  database:
    image: mariadb:11
    container_name: devops-mariadb
    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: devopsdb
      MYSQL_USER: devopsuser
      MYSQL_PASSWORD: devopspassword

    volumes:
      - mariadb_data:/var/lib/mysql

    ports:
      - "3306:3306"

volumes:
  mariadb_data:
