api:
  dashboard: true
  insecure: true

entryPoints:
  web:
    address: ":80"

  websecure:
    address: ":443"

providers:
  swarm:
    exposedByDefault: false
    network: traefik-public
  file:
    directory: /dynamic
    watch: true
