pipeline {
    agent any

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build Docker Image') {
            steps {
                sh '''
                docker build -t flask-cicd ./projects/15-jenkins/app
                '''
            }
        }

        stage('Run Container') {
            steps {
                sh '''
                docker rm -f flask-cicd || true

                docker run -d \
                    --name flask-cicd \
                    -p 5001:5000 \
                    flask-cicd
                '''
            }
        }

        stage('Test Application') {
            steps {
                sh '''
                sleep 5

                docker exec flask-cicd python -c "
import urllib.request
print(urllib.request.urlopen('http://localhost:5000').read().decode())
"
                '''
            }
        }
    }

    post {
        success {
            echo 'Pipeline completed successfully!'
        }

        failure {
            echo 'Pipeline failed!'
        }
    }
}
